sort or indent only

diff --git a/templates/tests/test-connection.yaml b/templates/tests/test-connection.yaml
--- a/templates/tests/test-connection.yaml
+++ b/templates/tests/test-connection.yaml
@@ -1,32 +1,33 @@
 apiVersion: v1
 kind: Pod
 metadata:
+  annotations:
+    "helm.sh/hook": test
   name: "{{ include "liferay.fullname" . }}-test-connection"
   namespace: {{ include "liferay.namespace" . | quote }}
   labels:
     {{- include "liferay.labels" . | nindent 4 }}
-  annotations:
-    "helm.sh/hook": test
 spec:
   containers:
-    - name: test-connection
-      image: busybox:latest
-      command: ["/bin/sh","-c"]
-      args:
-        - |
-          trap 'echo "Received signal to Terminate"; exit 0' SIGINT SIGTERM
-          START=$(date +%s)
+  - command:
+    - /bin/sh
+    - -c
+    - |
+      trap 'echo "Received signal to Terminate"; exit 0' SIGINT SIGTERM
+      START=$(date +%s)
 
-          # Only wait for 5 minutes and then fail
-          until nc -vz -w 2 {{ include "liferay.fullname" . }} {{ (index .Values.service.ports 0).port }}; do
-            NOW=$(date +%s)
-            SPAN=$(($NOW - $START))
-            if [ $SPAN -gt 300 ]; then
-              echo "DXP Service did not arrive within expected time (5 mins)."
-              exit 1
-            fi
-            echo "Waiting for DXP service"
-            sleep 2
-          done
+      # Only wait for 5 minutes and then fail
+      until nc -vz -w 2 {{ include "liferay.fullname" . }} {{ (index .Values.service.ports 0).port }}; do
+        NOW=$(date +%s)
+        SPAN=$(($NOW - $START))
+        if [ $SPAN -gt 300 ]; then
+          echo "DXP Service did not arrive within expected time (5 mins)."
+          exit 1
+        fi
+        echo "Waiting for DXP service"
+        sleep 2
+      done
+    image: busybox:latest
+    name: test-connection
   restartPolicy: Never
   serviceAccountName: {{ include "liferay.serviceAccountName" . }}
